server:
  port: 8080

spring:
  application:
    name: digital-avatar-web
  profiles:
    active: prod
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  type-aliases-package: com.web
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  #JWT存储的请求头
  requestHeader: Authorization
  #JWT加解密使用的密钥
  secret: digital.avatar
  #JWT的有效时间(60*60*24*7)
  expiration: 604800
  #JWT负载中的开头
  tokenStartWith: 'Bearer '
