server:
  port: 8080

spring:
  application:
    name: digital-avatar-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/assess?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  global-config:
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  #JWT存储的请求头
  requestHeader: Authorization
  #JWT加解密使用的密钥
  secret: digital.avatar
  #JWT的有效时间(60*60*24*7)
  expiration: 604800
  #JWT负载中的开头
  tokenStartWith: 'Bearer '
